
all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/azhar_west-2_oregon.pem
  
az_a_hosts:
  hosts:
    ip-172-32-48-77.us-west-2.compute.internal:
    ip-172-32-51-129.us-west-2.compute.internal:
    ip-172-32-56-209.us-west-2.compute.internal:
    ip-172-32-62-207.us-west-2.compute.internal:
    ip-172-32-62-143.us-west-2.compute.internal:

az_b_hosts:
  hosts:
    ip-172-32-76-13.us-west-2.compute.internal:
    ip-172-32-64-100.us-west-2.compute.internal:
    ip-172-32-68-7.us-west-2.compute.internal:
    ip-172-32-78-9.us-west-2.compute.internal:

az_c_hosts:
  hosts:
    ip-172-32-91-47.us-west-2.compute.internal:
    ip-172-32-80-102.us-west-2.compute.internal:



zookeeper:
  hosts:
    ip-172-32-48-77.us-west-2.compute.internal:
    ip-172-32-76-13.us-west-2.compute.internal:
    ip-172-32-91-47.us-west-2.compute.internal:
    ip-172-32-51-129.us-west-2.compute.internal:
    ip-172-32-64-100.us-west-2.compute.internal:

kafka_broker:
  hosts:
    ip-172-32-56-209.us-west-2.compute.internal:
    ip-172-32-68-7.us-west-2.compute.internal:
    ip-172-32-80-102.us-west-2.compute.internal:
    ip-172-32-62-207.us-west-2.compute.internal:

schema_registry:
  hosts:
    ip-172-32-62-143.us-west-2.compute.internal:
    ip-172-32-78-9.us-west-2.compute.internal:

